import Head from 'next/head'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navigation from '@/Components/Navigation'
import About from '@/Components/About'
import Mission from '@/Components/Mission'
import Business from '@/Components/Business'
import Work from '@/Components/Work'
import Signup from '@/Components/Signup'
import Experience from '@/Components/Experience'
import Footnav from '@/Components/Footnav'


const title= "Mission"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Lexend+Deca:wght@200;300;400;500;600;700&family=Roboto+Condensed:wght@300;400;700&family=Roboto:ital,wght@0,300;0,400;0,500;1,100;1,300&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
      <Navigation/>
      <Mission/>
      <About/>
      <Business/>
      <Work/>
      <Experience/>
      <Footnav/>
     
      </main>
      
    </div>
  )
}



